const categories = [
  "Electronics",
  "Clothing",
  "Food",
  "Books",
  "Home & Kitchen",
  "Beauty",
  "Sports",
  "Automotive",
  "Toys & Games",
  "Health",
  "Pet Supplies",
  "Office Supplies",
  "Baby & Kids",
  "Jewelry",
  "Music",
  "Arts & Crafts",
  "Garden",
  "Tools",
  "Shoes",
  "Bags & Luggage",
  "Furniture",
  "Groceries",
  "Phones & Tablets",
  "Computers & Laptops",
  "Cameras",
  "Smart Home",
  "Stationery",
];

export default categories;
